### ISSUE TITLE
agent.GatherCandidates stuck on mac  

### ISSUE THREAD

**Issue by notedit** [PeterXu/xrtc#1]
I just  run agent_test.go to test the agent.   it seems GatherCandidates just stuck, and does not return.

**Comment by PeterXu** [comment]
It is caused by golang link issue in MacOS.
You can use docker to build/run.

make docker-pull
make docker-mac
make deploy-mac

**Comment by notedit** [comment]
It works.  I want to know which golang link issue make it does not work on macos

**Comment by PeterXu** [comment]
cgo link c-lib, like: https://github.com/golang/go/issues/26073

**Comment by notedit** [comment]
Thanks
